"""added image urls to News

Revision ID: 0f63be587d6c
Revises: 90f03d4a707e
Create Date: 2020-07-20 20:40:42.824932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f63be587d6c'
down_revision = '90f03d4a707e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('News', sa.Column('image_url', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('News', 'image_url')
    # ### end Alembic commands ###
