"""upd products, add events

Revision ID: 9f5d4aa9d445
Revises: 0339261c3055
Create Date: 2020-07-23 22:30:07.794573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5d4aa9d445'
down_revision = '0339261c3055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('Product', sa.Column('male', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Product', 'male')
    op.drop_column('Product', 'brand')
    # ### end Alembic commands ###
