"""updated materials ent

Revision ID: a5e949ec7eed
Revises: 9f5d4aa9d445
Create Date: 2020-07-24 17:43:58.392460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e949ec7eed'
down_revision = '9f5d4aa9d445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_materials',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['Material.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_materials')
    # ### end Alembic commands ###
